# Site settings
title: David Janus
email: davidjanus17@gmail.com
url: https://davidjanus.com
description: "Spokesman and Speechwriter"
location: "Los Angeles, CA"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: David Janus

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/davidjanus22

# Build settings
markdown: kramdown
permalink: pretty